### PR TITLE
fix windows not tiling after changing desktops or activities

### LINKED ISSUE #363: [Bug]: Tiling is bugged on new kwin version (5.25 beta)
### Summary

On new `kwin` version (5.25 beta) windows tiling doesn't update when offscreen / not on currently visible desktop. So e.g. if a window was closed offscreen, Bismuth keeps empty space until you force tiling update in some way (open new window, close some window, change layout etc.).
I suppose devs changed behavior regarding offscreen windows layout update.

### Steps to Reproduce

Use latest plasma 5.25 beta.

### Expected behavior

Should work as on earlier versions.

### Screenshots

_No response_

### Bismuth version

3.1.1

### KDE Plasma version

5.25

### The platform KWin is running on

X11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by benemorius**
## Summary

Currently the signals we're getting from kwin aren't causing us to retile windows when they're moved between desktops or activities. This PR connects the signals so we trigger a retile when either the desktop or activity is changed.

## Test Plan

* move a window from the current desktop/activity to a different one
* switch to that desktop/activity
* without this fix, the desktop/activity is not tiled to reflect the moved window

## Related Issues

Closes #363

### CODE REVIEW

File: src/kwinscript/driver/index.ts [hunk 1]
```diff
@@ -380,6 +380,14 @@ export class DriverImpl implements Driver {
     this.connect(client.shadeChanged, () => {
       this.controller.onWindowShadeChanged(window);
     });
+
+    this.connect(this.kwinApi.workspace.currentActivityChanged, () =>
```
Comment (gikari) [inline src/kwinscript/driver/index.ts:384]: Those signals belong to the entire workspace and not a window. Therefore, the connections should be placed inside the `bindEvents` function.

File: src/kwinscript/extern/kwin.d.ts [hunk 2]
```diff
@@ -60,12 +60,20 @@ declare namespace KWin {
...
     numberScreensChanged: QSignal;
     screenResized: QSignal;
 
+    /**
+     * Emitted when the activity changes. One signal is sent per each window.
+     */
+    currentActivityChanged: QSignal;
+
+    /**
+     * Emitted when the desktop changes. One signal is sent per each window.
```
Comment (gikari) [inline src/kwinscript/extern/kwin.d.ts:73]: The same questions.

File: src/kwinscript/driver/index.ts [hunk 3]
```diff
@@ -380,6 +380,14 @@ export class DriverImpl implements Driver {
...
+      this.controller.onCurrentSurfaceChanged()
+    );
+
+    this.connect(this.kwinApi.workspace.currentDesktopChanged, () =>
```
Comment (gikari) [inline src/kwinscript/driver/index.ts:388]: Same.

**Review by gikari — CHANGES_REQUESTED** [review]
Nice catch. It's very strange, that those signals were not previously connected.

**Comment by benemorius** [comment]
> Those signals belong to the entire workspace and not a window. Therefore, the connections should be placed inside the bindEvents function.

That! That explains the event-per-window behavior. I was sure that was buggy behavior, that's why I documented it, but I was looking for the problem in kwin.

I moved it out of the window events and of course now I'm not getting those duplicate events anymore. I pushed an update.

I'm assuming we used to be triggering arranging incidentally from some other signal that kwin used to send and doesn't anymore and that's why these missing signals weren't being noticed. Although I get the same behavior with kwin 5.21.4 so I dunno.

**Review by gikari — APPROVED** [review]
